"""
Django settings for cloth_store project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production-please')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition



INSTALLED_APPS = [
    'django.contrib.admin',         # Required for admin
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Your apps
    'apps.users',
    'apps.products',
    'apps.orders',
    'apps.dashboard',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # you can add template folders if needed
        'APP_DIRS': True,  # important for admin
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # required
                'django.contrib.auth.context_processors.auth',  # required
                'django.contrib.messages.context_processors.messages',  # required
            ],
        },
    },
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',       # must be before auth
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',    # required
    'django.contrib.messages.middleware.MessageMiddleware',       # required
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# ============================================================
#  Database — MySQL (your existing Cloth_Store schema)
# ============================================================
DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.mysql',
        'NAME':     config('DB_NAME',     default='Cloth_Store'),
        'USER':     config('DB_USER',     default='Th34n'),
        'PASSWORD': config('DB_PASSWORD', default='Th34n90s'),
        'HOST':     config('DB_HOST',     default='127.0.0.1'),
        'PORT':     config('DB_PORT',     default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# ============================================================
#  Django REST Framework
# ============================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.users.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',   # for image uploads
        'rest_framework.parsers.FormParser',
    ),
}




ROOT_URLCONF = 'cloth_store.urls'       # points to your main urls.py
WSGI_APPLICATION = 'cloth_store.wsgi.application'  # points to wsgi.py in backend folder


from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

#  CORS — allow React dev server to call Django
# ============================================================
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',    # Vite dev server
    'http://127.0.0.1:5173',
]



CORS_ALLOW_CREDENTIALS = True



CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'origin',
    'x-csrftoken',
    'x-requested-with',
]




MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'    # product images go here


# URL prefix for static files (CSS, JS, images)
STATIC_URL = '/static/'

# Optional: directory to collect static files (used in production)
STATIC_ROOT = BASE_DIR / 'staticfiles'




# ============================================================
#  Default primary key
# ============================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'